<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-VkBot-19240822-1721-4ee3-95ab-aa85fc61ce6b</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>TelegramBot</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.5" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.5" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.5" />
        <PackageReference Include="Telegram.Bot" Version="22.9.5.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Application\Application.csproj" />
      <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>
</Project>
